// src/popup/src/components/Slider.tsx
import React, { useState } from 'react';

interface Slider {
  onValueChange: (value: number) => void;
}

const Slider: React.FC<Slider> = ({ onValueChange }) => {
  const [sliderValue, setSliderValue] = useState(0);

  const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const value = parseInt(event.target.value, 10);
    setSliderValue(value);
  };

  const handleMouseUp = () => {
    onValueChange(sliderValue);
  };

  return (
    <div className="relative">
      <input
        type="range"
        min="0"
        max="100"
        value={sliderValue}
        onChange={handleInputChange}
        onMouseUp={handleMouseUp}
        className="absolute w-full h-1.5 bg-gray-300 rounded-full cursor-pointer focus:outline-none"
      />
    </div>
  );
};

export default Slider;

// src/svelte-interface/components/Slider.svelte
<script lang="ts">
  export let state: number;
  export let onChange: (value: number) => void;
</script>

<div class="relative w-full max-w-lg py-8 mx-auto">
  <input
    type="range"
    min="0"
    max="100"
    bind:value={state}
    on:change={(e) => onChange(Number(e.currentTarget.value))}
    class="w-full h-1 rounded-full appearance-none cursor-pointer dark:bg-[#38373D] bg-[#DDDDDD] slider"
  />
</div>

<style>
  .slider::-webkit-slider-thumb {
    -webkit-appearance: none;
    width: 24px;
    height: 24px;
    box-shadow: 0px 0px 8px 0px rgba(0, 0, 0, 0.3);
    background: white;
    cursor: pointer;
    border-radius: 50%;
  }

  .slider::-moz-range-thumb {
    width: 24px;
    height: 24px;
    box-shadow: 0px 0px 8px 0px rgba(0, 0, 0, 0.3);
    background: white;
    cursor: pointer;
    border-radius: 50%;
  }
</style>
