// src/old-interface/components/Switch.tsx
import { motion } from "framer-motion";
import "./Switch.css";
import type { SwitchProps } from "../types/SwitchProps";
import { memo } from "react";

function Switch(props: SwitchProps) {
  const toggleSwitch = () => {
    const newIsOn = !props.state;
    props.onChange(newIsOn);
  };

  return (
    <div
      className="flex w-14 p-1 cursor-pointer rounded-full dark:bg-[#38373D] bg-[#DDDDDD] switch"
      data-ison={props.state}
      onClick={toggleSwitch}
    >
      <motion.div
      
        className="w-6 h-6 bg-white dark:bg-[#FEFEFE] rounded-full drop-shadow-md"
        initial={{ x: props.state ? 0 : 0 }}
        animate={{ x: props.state ? 24 : 0 }}
        transition={spring}
        />
    </div>
  );
}

const spring = {
  type: "spring",
  stiffness: 700,
  damping: 30
};

export default memo(Switch);

// src/svelte-interface/components/Switch.svelte
<script lang="ts">
  import { animate, spring } from 'motion';
  import { onMount } from "svelte";

  let { state, onChange } = $props<{ state: boolean, onChange: (newState: boolean) => void }>();

  let handle: HTMLElement | null = null;

  const toggleSwitch = () => {
    onChange(!state);
  };

  const springParams = {
    stiffness: 700,
    damping: 30,
  };

  const animateSwitch = (enabled: boolean) => {
    if (handle) {
      animate(
        handle,
        { x: enabled ? 20 : 0 },
        {
          easing: spring(springParams),
        }
      );
    }
  };

  // Trigger animation whenever state changes
  $effect(() => animateSwitch(state));

  onMount(() => {
    // Initialize the position of the switch
    animateSwitch(state);
  });
</script>

<div
  class="flex w-14 p-1 cursor-pointer transition rounded-full dark:bg-[#38373D] bg-[#DDDDDD] switch"
  data-ison={state}
  onclick={toggleSwitch}
  onkeydown={(e) => e.key === "Enter" && toggleSwitch()}
  role="switch"
  aria-checked={state}
  tabindex="0"
>
  <div
    bind:this={handle}
    class="w-6 h-6 bg-white dark:bg-[#FEFEFE] rounded-full drop-shadow-md"
  ></div>
</div>

<style>
  .dark .switch[data-ison="true"],
  .switch[data-ison="true"] {
    background-color: #30D259;
  }
</style>
