// src/interface/components/TabbedContainer.tsx
import React, { useState, useRef, useEffect, memo } from 'react';
import { motion } from 'framer-motion';
import type { TabbedContainerProps } from '../types/TabbedContainerProps';

const TabbedContainer: React.FC<TabbedContainerProps> = ({ tabs }) => {
  const [activeTab, setActiveTab] = useState(0);
  const [hoveredTab, setHoveredTab] = useState<number | null>(null);
  const [tabWidth, setTabWidth] = useState(0);
  const [position, setPosition] = useState(0);
  const positionRef = useRef(position);


    // Function to handle message
    const handleMessage = (event: MessageEvent) => {
      if (event.data === "popupClosed") {  
        setActiveTab(0);
      }
    };
  
    useEffect(() => {
      // Add event listener for 'message' event
      window.addEventListener("message", handleMessage);
  
      // Cleanup
      return () => {
        window.removeEventListener("message", handleMessage);
      };
    }, []);


  useEffect(() => {
    const newPosition = -activeTab * 100;
    setPosition(newPosition);
    positionRef.current = newPosition;
  }, [activeTab]);

  const containerRef = useRef(null);

  const springTransition = { type: 'spring', stiffness: 250, damping: 25 };

  useEffect(() => {
    if (containerRef.current) {
      // @ts-expect-error for some reason its giving an error in TS but it works...
      const width = containerRef.current.getBoundingClientRect().width;
      setTabWidth(width / tabs.length);
    }
  }, [tabs.length]);

  const calcXPos = (index: number | null) => {
    if (index !== null) {
      return tabWidth * index;
    }
    return tabWidth * activeTab;
  };

  return (
    <>
    <div ref={containerRef} className="top-0 z-10 text-[0.875rem] pb-0.5 mx-4">
      <div className="relative flex">          
        <motion.div
          className="absolute top-0 left-0 z-0 h-full bg-[#DDDDDD] dark:bg-[#38373D] rounded-full opacity-40"
          style={{ width: `${tabWidth}px` }}
          initial={false}
          animate={{ x: calcXPos(hoveredTab) }}
          transition={springTransition}
        />
        {tabs.map((tab, index) => (
          <button
            key={index}
            className="relative z-10 flex-1 px-4 py-2"
            onClick={() => setActiveTab(index)}
            onMouseEnter={() => setHoveredTab(index)}
            onMouseLeave={() => setHoveredTab(null)}
          >
            {tab.title}
          </button>
        ))}
      </div>
    </div>
    <div className="h-full px-4 overflow-y-scroll overflow-x-clip">
        <motion.div
          initial={false}
          animate={{ x: `${position}%` }}
          transition={springTransition}
        >
          <div className="flex">
            {tabs.map((tab, index) => (
            <div key={index} className={`absolute w-full transition-opacity duration-300 pb-4 ${activeTab === index ? 'opacity-100' : 'opacity-0'}`}
              style={{left: `${index * 100}%`}}>
                {tab.content}
              </div>
            ))}
          </div>
        </motion.div>
      </div>
    </>
  );
};

export default memo(TabbedContainer);

// src/svelte-interface/components/TabbedContainer.svelte
<script lang="ts">
  // @ts-expect-error umm idk
  import { MotionDiv } from 'svelte-motion';
  import './TabbedContainer.css';
  import type { Component } from 'svelte'
  import { onMount } from 'svelte';

  let { tabs } = $props<{ tabs: { title: string, Content: Component }[] }>();
  let activeTab = $state(0);
  let hoveredTab = $state<number | null>(null);
  let containerRef: HTMLElement | null = null;
  let tabWidth = $state(0);

  const springTransition = { type: 'spring', stiffness: 250, damping: 25 };

  const updateTabWidth = () => {
    tabWidth = tabs.length > 0 ? 100 / tabs.length : 0;
    if (!containerRef) return;
    containerRef.style.setProperty('--tab-width', `${tabWidth}%`);
  };

  const calcXPos = (index: number | null) => {
    if (containerRef) {
      return tabWidth * (index !== null ? index : activeTab) * containerRef.getBoundingClientRect().width / 100;
    }
    return 0;
  };

  $effect(() => {
    calcXPos(hoveredTab);
  });

  onMount(() => {
    updateTabWidth();

    const handleMessage = (event: MessageEvent) => {
      if (event.data === "popupClosed") {
        activeTab = 0;
      }
    };
    window.addEventListener("message", handleMessage);

    return () => {
      window.removeEventListener("message", handleMessage);
    };
  });

  /* $effect(() => {
    if (tabs.length > 0) {
      updateTabWidth();
    }
  }); */
</script>

<div bind:this={containerRef} class="top-0 z-10 text-[0.875rem] pb-0.5 mx-4 tab-width-container">
  <div class="hidden tab-width"></div>
  <div class="relative flex">
    <MotionDiv
      class="absolute top-0 left-0 z-0 h-full bg-[#DDDDDD] dark:bg-[#38373D] rounded-full opacity-40"
      animate={{ x: calcXPos(hoveredTab) }}
      style="width: var(--tab-width)"
      transition={springTransition}
    />
    {#each tabs as { title }, index}
      <button
        class="relative z-10 flex-1 px-4 py-2"
        onclick={() => activeTab = index}
        onmouseenter={() => hoveredTab = index}
        onmouseleave={() => hoveredTab = null}
      >
        {title}
      </button>
    {/each}
  </div>
</div>
<div class="h-full px-4 overflow-y-scroll overflow-x-clip">
  <MotionDiv
    animate={{ x: `${-activeTab * 100}%` }}
    transition={springTransition}
  >
    <div class="flex">
      {#each tabs as { Content }, index}
        <div class="absolute w-full transition-opacity duration-300 pb-4 {activeTab === index ? 'opacity-100' : 'opacity-0'}"
          style="left: {index * 100}%;">
          <Content />
        </div>
      {/each}
    </div>
  </MotionDiv>
</div>

<style>
  .tab-width {
    width: var(--tab-width);
  }
</style>
